### ISSUE TITLE
一种更简单的手动安装方法

### ISSUE THREAD

**Issue by sanjusss** [catscarlet/wp-ipip#2]
下载最新release版的zip代码后，例如 [https://github.com/catscarlet/wp-ipip/archive/v3.0.2.zip](https://github.com/catscarlet/wp-ipip/archive/v3.0.2.zip)，将zip内的文件夹改名为wp-ipip，即可直接在后台插件安装界面上传安装。

**Comment by catscarlet** [comment]
已考虑在下个版本中添加这个方法和相关文档。

**Comment by catscarlet** [comment]
Fixed in #3.
